version: '3.4'

services:
  db:
    image: postgres
    restart: unless-stopped
    env_file:
      - '.env'
    environment:
      - PGUSER=${POSTGRES_USER}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes: 
      - './.data/postgres:/var/lib/postgresql/data'
      - './migrations/:/docker-entrypoint-initdb.d/'
    networks:
      - watchtower
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 4s
      timeout: 5s
      retries: 15

  cache:
    image: redis:7.2-rc
    restart: unless-stopped
    ports:
      - '${REDIS_PORT}:6379'
    command: redis-server --save 20 1
    networks:
      - watchtower
    volumes: 
      - './.data/redis:/data'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  recorder:
    build: ./recorder
    networks:
      - watchtower
    links:
      - cache
    env_file:
      - '.env'
    environment:
      - REDIS_HOST=cache
    deploy:
      replicas: 10
    depends_on:
      cache:
        condition: service_healthy

  api:
    build: ./api
    ports:
      - '${API_PORT}:80'
    networks:
      - watchtower
    links:
      - db
      - cache
    env_file:
      - '.env'
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=cache
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy

  processor:
    build: ./processor
    networks:
      - watchtower
    links:
      - db
      - cache
    env_file:
      - '.env'
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=cache
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy

networks:
  watchtower:
    driver: bridge
