version: '3.4'

services:
  db:
    image: postgres
    restart: unless-stopped
    env_file:
      - '.env'
    environment:
      - PGUSER=${POSTGRES_USER}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes: 
      - './.data/postgres:/var/lib/postgresql/data'
      - './migrations/:/docker-entrypoint-initdb.d/'
    networks:
      - watchtower
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 4s
      timeout: 5s
      retries: 15

  cache:
    image: redis:7.2-rc
    restart: unless-stopped
    ports:
      - '${REDIS_PORT}:6379'
    command: redis-server --save 20 1
    networks:
      - watchtower
    volumes: 
      - './.data/redis:/data'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # TODO: Add services

networks:
  watchtower:
    driver: bridge
